### ISSUE TITLE
Don't redirect in service classes

### ISSUE THREAD

**Issue by yungifez** [ahmed-fawzy99/hr-management-system#1]
The point of service classes is to decouple business logic from controllers, which allows you to reuse code, eg when using multiple end points

Imagine if you had an api, a redirection in service classes would lead to issues

Or imagine you want to use the service class in a queue or somewhere else 

So anything that is specific to an endpoint eg sessions etc should not be in service classes

So don't do this
```php
    public function renderShowPage($id, $request): \Inertia\Response 
     { 
      ...........
         return Inertia::render('Position/PositionView', [ 
             'position' => $position, 
             'employees' => $employees 
         ]); 
     } 
 
```

**Comment by ahmed-fawzy99** [comment]
Thanks for the valuable feedback! I've adjusted this logic for all controllers in the last commit.
